---
# Boulder SCT Provider Service
apiVersion: v1
kind: Service
metadata:
  name: boulder-ra-sct-provider
  namespace: boulder
  labels:
    app: boulder-sct-provider
    app.kubernetes.io/name: boulder-sct-provider
    app.kubernetes.io/component: sct-provider
    app.kubernetes.io/part-of: boulder
spec:
  type: ClusterIP
  ports:
    - port: 9999
      targetPort: 9999
      protocol: TCP
      name: grpc
  selector:
    app: boulder-sct-provider
