# pkimetal linting disabled - service not deployed in dev
# To enable, deploy boulder-pkimetal service and uncomment below

# [e_pkimetal_lint_cabf_serverauth_cert]
# addr = "http://boulder-pkimetal.boulder.svc.cluster.local:8080"
# severity = "notice"
# timeout = 2000000000 # 2 seconds
# ignore_lints = [
#   "pkilint:cabf.serverauth.dv.common_name_attribute_present",
#   "zlint:w_subject_common_name_included",
#   "pkilint:cabf.serverauth.subscriber.subject_key_identifier_extension_present",
#   "zlint:w_ext_subject_key_identifier_not_recommended_subscriber",
#   "pkilint:cabf.serverauth.subscriber_rsa_digitalsignature_and_keyencipherment_present",
# ]

# [e_pkimetal_lint_cabf_serverauth_crl]
# addr = "http://boulder-pkimetal.boulder.svc.cluster.local:8080"
# severity = "notice"
# timeout = 2000000000 # 2 seconds
# ignore_lints = []
