apiVersion: apps/v1
kind: Deployment
metadata:
  name: boulder-email-exporter
  labels:
    app.kubernetes.io/name: boulder-email-exporter
    app.kubernetes.io/component: email-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: boulder-email-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: boulder-email-exporter
        app.kubernetes.io/component: email-exporter
    spec:
      containers:
        - name: boulder-email-exporter
          image: letsencrypt/boulder:latest
          args:
            - boulder
            - email-exporter
            - --config
            - /config/email-exporter.json
          ports:
            - name: grpc
              containerPort: 9381
              protocol: TCP
            - name: metrics
              containerPort: 8025
              protocol: TCP
          livenessProbe:
            grpc:
              port: 9381
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            grpc:
              port: 9381
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
            - name: ipki-ca
              mountPath: /certs/ipki/ca.crt
              subPath: ca.crt
              readOnly: true
            - name: ipki-service
              mountPath: /certs/ipki/email-exporter
              readOnly: true
            - name: secrets
              mountPath: /secrets
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: boulder-email-exporter-config
        - name: ipki-ca
          secret:
            secretName: boulder-internal-ca
        - name: ipki-service
          secret:
            secretName: boulder-email-exporter-grpc-tls
        - name: secrets
          secret:
            secretName: boulder-email-exporter-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: boulder-email-exporter
  labels:
    app.kubernetes.io/name: boulder-email-exporter
    app.kubernetes.io/component: email-exporter
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 9381
      targetPort: grpc
    - name: metrics
      port: 8025
      targetPort: metrics
  selector:
    app.kubernetes.io/name: boulder-email-exporter
