apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "softhsm-proxy.fullname" . }}-config
  labels:
    {{- include "softhsm-proxy.labels" . | nindent 4 }}
data:
  softhsm2.conf: |
    directories.tokendir = /var/lib/softhsm/tokens
    objectstore.backend = file
    log.level = INFO
