apiVersion: v1
kind: Service
metadata:
  name: {{ include "softhsm-proxy.fullname" . }}
  labels:
    {{- include "softhsm-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: pkcs11
      protocol: TCP
      name: pkcs11
  selector:
    {{- include "softhsm-proxy.selectorLabels" . | nindent 4 }}
