# Default values for boulder.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: boulder
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

service:
  type: ClusterIP
  port: 4000


config:
  boulder: {}

mariadb:
  enabled: false
  image:
    tag: "11.4"
    pullPolicy: IfNotPresent
  auth:
    rootPassword: "changeme"
    database: "boulder"
    username: "boulder"
    password: "changeme"

proxysql:
  enabled: false
  auth:
    adminUsername: "admin"
    adminPassword: "changeme"
    monitorUsername: "monitor"
    monitorPassword: "changeme"
  backend:
    host: "boulder-mariadb"
    port: 3306

redis:
  enabled: false
  image:
    tag: "7.2"
    pullPolicy: IfNotPresent
  auth:
    password: "changeme"

consul:
  enabled: false
  image:
    tag: "1.18"
    pullPolicy: IfNotPresent

jaeger:
  enabled: false
  image:
    tag: "1.57"
    pullPolicy: IfNotPresent
