apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.next.yml --out k8s/
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: bmysql
  name: bmysql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: bmysql
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.next.yml --out k8s/
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: bmysql
    spec:
      containers:
        - args:
            - mysqld
            - --bind-address=0.0.0.0
            - --slow-query-log
            - --log-output=TABLE
            - --log-queries-not-using-indexes=ON
          env:
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "no"
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: boulder-mysql-sa-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: boulder-mysql-sa-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              value: boulder_sa_integration
            - name: MYSQL_RO_USER
              value: sa_ro
            - name: MYSQL_RO_PASSWORD
              value: example-sa-password
          image: mariadb:10.6.22
          name: bmysql
          volumeMounts:
            - name: mariadb-init-sql
              mountPath: /docker-entrypoint-initdb.d/mariadb-init-sa_ro.sql
              subPath: mariadb-init-sa_ro.sql
            - name: mariadb-init-sql
              mountPath: /docker-entrypoint-initdb.d/mariadb-init-incidents_sa.sql
              subPath: mariadb-init-incidents_sa.sql
      restartPolicy: Always
      volumes:
        - name: mariadb-init-sql
          configMap:
            name: mariadb-init-sql
