apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.next.yml --out k8s/
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: boulder
  name: boulder
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: boulder
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.next.yml --out k8s/
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: boulder
    spec:
      containers:
        - command:
            - test/entrypoint.sh
          env:
            - name: BOULDER_CONFIG_DIR
              value: test/config-next
            - name: FAKE_DNS
              value: 64.112.117.122
            - name: GOCACHE
              value: /boulder/.gocache/go-build-next
            - name: GOFLAGS
              value: -mod=vendor
          image: boulder:local
          imagePullPolicy: IfNotPresent
          name: boulder
          ports:
            - containerPort: 4001
              protocol: TCP
            - containerPort: 4002
              protocol: TCP
            - containerPort: 4003
              protocol: TCP
          volumeMounts:
            - mountPath: /boulder/config
              name: boulder-cm0
          workingDir: /go/src/github.com/letsencrypt/boulder
      restartPolicy: Always
      volumes:
        - configMap:
            name: boulder-cm0
          name: boulder-cm0
