apiVersion: v1
data:
  aws_creds.ini: |
    [default]
    aws_access_key_id=AKIAIOSFODNN7EXAMPLE
    aws_secret_access_key=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  backfiller_dburl: |
    sa:example-sa-password@tcp(boulder-proxysql:6033)/boulder_sa_integration
  badkeyrevoker_dburl: |
    badkeyrevoker:example-sa-password@tcp(boulder-proxysql:6033)/boulder_sa_integration
  cert_checker_dburl: |
    cert_checker:example-sa-password@tcp(boulder-proxysql:6033)/boulder_sa_integration
  expiration_mailer_dburl: |
    mailer:example-sa-password@tcp(boulder-proxysql:6033)/boulder_sa_integration
  incidents_dburl: |
    incidents_sa:example-sa-password@tcp(boulder-mysql:3306)/incidents_sa_integration?readTimeout=14s&timeout=1s
  mailer_dburl: |
    mailer:example-sa-password@tcp(boulder-proxysql:6033)/boulder_sa_integration
  nonce_prefix_key: |
    b91cf7d66bb88a0c50893eff1ce61555d548d6cf614925082352714efe881e30
  ocsp_responder_dburl: |
    ocsp_resp:example-sa-password@tcp(boulder-proxysql:6033)/boulder_sa_integration?readTimeout=800ms&writeTimeout=800ms&timeout=100ms
  ocsp_responder_redis_password: |
    0e5a4c8b5faaf3194c8ad83c3dd9a0dd8a75982b
  purger_dburl: |
    purger:example-sa-password@tcp(boulder-proxysql:6033)/boulder_sa_integration
  ratelimits_redis_password: |
    824968fa490f4ecec1e52d5e34916bdb60d45f8d
  revoker_dburl: |
    revoker:example-sa-password@tcp(boulder-proxysql:6033)/boulder_sa_integration
  rocsp_tool_password: |
    e4e9ce7845cb6adbbc44fb1d9deb05e6b4dc1386
  sa_dburl: |
    sa:example-sa-password@tcp(boulder-mysql:3306)/boulder_sa_integration?readTimeout=14s&writeTimeout=14s&timeout=1s
  sa_redis_password: de75ae663596735b90e461e5924f71a4c5f622ab
  sa_ro_dburl: |
    sa_ro:example-sa-password@tcp(boulder-mysql:3306)/boulder_sa_integration?readTimeout=14s&writeTimeout=14s&timeout=1s
  salesforce_client_id: |
    test-client-id
  salesforce_client_secret: |
    you-shall-not-pass
  sfe_unpause_key: |
    b18bd0dcf7113ef660e25457dbfc2162b1b3b17c0113abdc759af4752d8a90b5
  smtp_password: |
    password
  wfe_ratelimits_redis_password: |
    b3b2fcbbf46fe39fd522c395a51f84d93a98ff2f
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: boulder-secrets
