apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.next.yml --out k8s/
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: boulder
  name: boulder
spec:
  ports:
    - name: "4001"
      port: 4001
      targetPort: 4001
    - name: "4002"
      port: 4002
      targetPort: 4002
    - name: "4003"
      port: 4003
      targetPort: 4003
  selector:
    io.kompose.service: boulder
