apiVersion: v1
kind: Service
metadata:
  name: boulder-proxysql
  labels:
    io.kompose.service: bproxysql
spec:
  selector:
    io.kompose.service: bproxysql
  ports:
    - name: mysql
      port: 6033
      targetPort: 6033
    - name: admin
      port: 6032
      targetPort: 6032
  type: ClusterIP
