apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.next.yml --out k8s/
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: bproxysql
  name: bproxysql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: bproxysql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.next.yml --out k8s/
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: bproxysql
    spec:
      containers:
        - command:
            - proxysql
            - -f
            - --idle-threads
            - -c
            - /etc/proxysql/proxysql.cnf
            - --initial
          image: proxysql/proxysql:2.5.4
          name: bproxysql
          volumeMounts:
            - name: proxysql-config
              mountPath: /etc/proxysql
      volumes:
        - name: proxysql-config
          configMap:
            name: proxysql-config
      restartPolicy: Always
