apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.next.yml --out k8s/
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: bredis-1
  name: bredis-1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: bredis-1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.next.yml --out k8s/
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: bredis-1
    spec:
      containers:
        - args:
            - redis-server
            - /redis-config/redis.conf
          image: redis:6.2.7
          name: bredis-1
          volumeMounts:
            - name: redis-config
              mountPath: /redis-config
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-config
          configMap:
            name: redis-config
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-1-pvc
      restartPolicy: Always
