apiVersion: v1
kind: ConfigMap
metadata:
  name: consul-config
data:
  config.hcl: |
    datacenter = "dc1"
    data_dir = "/consul/data"
    log_level = "INFO"
    server = true
    bootstrap_expect = 1
    bind_addr = "0.0.0.0"
    client_addr = "0.0.0.0"
    retry_join = ["127.0.0.1"]
    ui_config {
      enabled = true
    }
    connect {
      enabled = true
    }
    acl = {
      enabled = false
    }
