apiVersion: v2
name: softhsm-proxy
description: PKCS#11 proxy server with SoftHSM backend for Boulder dev/CI
type: application
version: 0.1.0
appVersion: "2.6.1"
keywords:
  - pkcs11
  - hsm
  - softhsm
  - boulder
maintainers:
  - name: boulder-k8s
