# Mount nonce HMAC key from wfe2-secrets for nonce services
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boulder-nonce-a
spec:
  template:
    spec:
      containers:
        - name: boulder-nonce
          volumeMounts:
            - name: secrets
              mountPath: /secrets
              readOnly: true
      volumes:
        - name: secrets
          secret:
            secretName: boulder-wfe2-secrets
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boulder-nonce-b
spec:
  template:
    spec:
      containers:
        - name: boulder-nonce
          volumeMounts:
            - name: secrets
              mountPath: /secrets
              readOnly: true
      volumes:
        - name: secrets
          secret:
            secretName: boulder-wfe2-secrets
