# Reduce replicas to 1 for dev environment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boulder-wfe2
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boulder-ra
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boulder-sa
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boulder-ca
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boulder-va
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boulder-rva1
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boulder-rva2
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boulder-rva3
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boulder-publisher
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boulder-nonce-a
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boulder-nonce-b
spec:
  replicas: 1
