apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-test"
  labels:
    app: {{ .Release.Name }}-boulder
  annotations:
    "helm.sh/hook": test
spec:
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-boulder
    spec:
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-boulder-config
      containers:
        - name: test
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "/boulder"
            - "-config"
            - "/etc/boulder/development.json"
            - "-test"
          volumeMounts:
            - name: config
              mountPath: /etc/boulder/development.json
              subPath: development.json
      restartPolicy: Never
