apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Release.Name }}-test"
  annotations:
    "helm.sh/hook": test-success
  labels:
    app: "{{ .Release.Name }}-test"
spec:
  containers:
    - name: boulder-test
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      command:
        - "/boulder"
        - "--version"
  restartPolicy: Never
